name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the "main" branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install  # Adjust this if your project doesn't use npm

    - name: Build Project
      run: npm run build  # Adjust this if your project has a different build command

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: npx firebase deploy --only hosting
